# Items matched from Korean (source of truth) + English translation
# Fields: category, category_en, name, name_en, brand, qty, price, notes, notes_en

ITEMS = [
    # 가구 / Furniture
    {"category": "가구", "category_en": "Furniture", "name": "책상 - 일자형", "name_en": "Desk", "brand": "Fursys", "qty": 36, "price": 50000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "책상 - 120도 책상", "name_en": "Desk - 120 Degrees", "brand": "Fursys", "qty": 6, "price": 40000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "사무용 의자", "name_en": "Office Chair", "brand": "Fursys", "qty": 42, "price": 30000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "탕비실 철제 스툴", "name_en": "Metal Stool", "brand": "-", "qty": 16, "price": 5000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "가구", "category_en": "Furniture", "name": "탕비실 플라스틱 우드 스툴", "name_en": "Plastic Stool", "brand": "-", "qty": 7, "price": 5000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "가구", "category_en": "Furniture", "name": "빈백", "name_en": "Beanbag", "brand": "요기보", "qty": 5, "price": 25000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "가구", "category_en": "Furniture", "name": "Fursys 반인분 소파", "name_en": "Half Couch", "brand": "Fursys", "qty": 2, "price": 50000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "Fursys 긴 브라운 테이블", "name_en": "Long Brown Table", "brand": "Fursys", "qty": 1, "price": 80000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "브라운 의자", "name_en": "Brown Chair", "brand": "-", "qty": 12, "price": 41800, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "브라운 소파", "name_en": "Brown Couch", "brand": "-", "qty": 1, "price": 50000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "회의실 의자", "name_en": "Meeting Room Chair", "brand": "Fursys", "qty": 39, "price": 20000, "notes": "회의실 1-4", "notes_en": "Meeting Room 1-4"},
    {"category": "가구", "category_en": "Furniture", "name": "회의실 1 책상", "name_en": "Meeting Room 1 Table", "brand": "Fursys", "qty": 1, "price": 50000, "notes": "회의실 1", "notes_en": "Meeting Room 1"},
    {"category": "가구", "category_en": "Furniture", "name": "회의실 2 책상", "name_en": "Meeting Room 2 Table", "brand": "Fursys", "qty": 1, "price": 60000, "notes": "회의실 2", "notes_en": "Meeting Room 2"},
    {"category": "가구", "category_en": "Furniture", "name": "회의실 3 책상", "name_en": "Meeting Room 3 Table", "brand": "Fursys", "qty": 1, "price": 70000, "notes": "회의실 3", "notes_en": "Meeting Room 3"},
    {"category": "가구", "category_en": "Furniture", "name": "회의실 4 책상", "name_en": "Meeting Room 4 Table", "brand": "Fursys", "qty": 1, "price": 60000, "notes": "회의실 4", "notes_en": "Meeting Room 4"},
    {"category": "가구", "category_en": "Furniture", "name": "사무실 메인 공간 테이블", "name_en": "Table", "brand": "-", "qty": 1, "price": 20000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "소형 원형 커피 테이블", "name_en": "Circular Marble Table", "brand": "-", "qty": 1, "price": 10000, "notes": "입구", "notes_en": "Entrance"},
    {"category": "가구", "category_en": "Furniture", "name": "탕비실 우드 슬랩 테이블 (대)", "name_en": "Break Room Wooden Slab Table (Large)", "brand": "-", "qty": 1, "price": 70000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "가구", "category_en": "Furniture", "name": "탕비실 우드 슬랩 테이블 (소)", "name_en": "Break Room Wooden Slab Table (Small)", "brand": "-", "qty": 1, "price": 50000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "가구", "category_en": "Furniture", "name": "탕비실 타원형 테이블", "name_en": "Break Room Table", "brand": "-", "qty": 1, "price": 45000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "가구", "category_en": "Furniture", "name": "탕비실 타원형 테이블 의자", "name_en": "Break Room Table Chair", "brand": "-", "qty": 4, "price": 15000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "가구", "category_en": "Furniture", "name": "탕비실 원형 테이블", "name_en": "Break Room Round Table", "brand": "-", "qty": 2, "price": 20000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "가구", "category_en": "Furniture", "name": "탕비실 원형 테이블 의자", "name_en": "Break Room Round Table Chair", "brand": "-", "qty": 2, "price": 15000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "가구", "category_en": "Furniture", "name": "입구 회의실 의자", "name_en": "Entrance Meeting Room Chair", "brand": "-", "qty": 6, "price": 25000, "notes": "입구", "notes_en": "Entrance"},
    {"category": "가구", "category_en": "Furniture", "name": "입구 소파", "name_en": "Entrance Couch", "brand": "KTA 한국TA", "qty": 2, "price": 50000, "notes": "입구", "notes_en": "Entrance"},
    {"category": "가구", "category_en": "Furniture", "name": "입구 옆 회의실 테이블", "name_en": "Entrance Meeting Room Table", "brand": "-", "qty": 1, "price": 30000, "notes": "입구", "notes_en": "Entrance"},
    {"category": "가구", "category_en": "Furniture", "name": "빨간색 쿠션 스툴", "name_en": "Red Cushion Stool", "brand": "Fursys", "qty": 4, "price": 10000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "미디어룸 테이블 (대)", "name_en": "Media Room Table (Large)", "brand": "-", "qty": 2, "price": 30000, "notes": "미디어룸", "notes_en": "Media Room"},
    {"category": "가구", "category_en": "Furniture", "name": "미디어룸 테이블 (소)", "name_en": "Media Room Table (Small)", "brand": "-", "qty": 1, "price": 15000, "notes": "미디어룸", "notes_en": "Media Room"},
    {"category": "가구", "category_en": "Furniture", "name": "(대) 활장 스탠드", "name_en": "Large Lamp", "brand": "-", "qty": 1, "price": 40000, "notes": "입구", "notes_en": "Entrance"},
    {"category": "가구", "category_en": "Furniture", "name": "가죽 의자", "name_en": "Leather Chair", "brand": "-", "qty": 1, "price": 40000, "notes": "입구", "notes_en": "Entrance"},
    {"category": "가구", "category_en": "Furniture", "name": "낮은 커피 테이블", "name_en": "Low Coffee Table", "brand": "-", "qty": 1, "price": 20000, "notes": "입구", "notes_en": "Entrance"},
    {"category": "가구", "category_en": "Furniture", "name": "선반 (대)", "name_en": "Shelf (Large)", "brand": "-", "qty": 1, "price": 20000, "notes": "Working Space 1", "notes_en": "Working Space 1"},
    {"category": "가구", "category_en": "Furniture", "name": "선반 (중)", "name_en": "Shelf (Small)", "brand": "-", "qty": 1, "price": 10000, "notes": "Working Space 1", "notes_en": "Working Space 1"},
    {"category": "가구", "category_en": "Furniture", "name": "서랍형 선반", "name_en": "Shelf with Drawers", "brand": "-", "qty": 1, "price": 25000, "notes": "Working Space 앞", "notes_en": "Front of Working Space"},
    {"category": "가구", "category_en": "Furniture", "name": "캐비닛", "name_en": "Cabinet", "brand": "-", "qty": 1, "price": 40000, "notes": "Working Space 앞", "notes_en": "Front of Working Space"},
    {"category": "가구", "category_en": "Furniture", "name": "사물함", "name_en": "Locker", "brand": "-", "qty": 1, "price": 80000, "notes": "Working Space 앞", "notes_en": "Front of Working Space"},
    {"category": "가구", "category_en": "Furniture", "name": "침대", "name_en": "Bed", "brand": "-", "qty": 1, "price": 25000, "notes": "휴게 공간", "notes_en": "Rest Area"},
    {"category": "가구", "category_en": "Furniture", "name": "끌차", "name_en": "Flat Dolly", "brand": "-", "qty": 2, "price": 20000, "notes": "창고", "notes_en": "Storage"},
    {"category": "가구", "category_en": "Furniture", "name": "사다리 (대)", "name_en": "Ladder (Large)", "brand": "-", "qty": 1, "price": 70000, "notes": "창고", "notes_en": "Storage"},
    {"category": "가구", "category_en": "Furniture", "name": "화분 선반", "name_en": "Shelf with Plants", "brand": "-", "qty": 3, "price": 10000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "플라스틱 쓰레기통 (대)", "name_en": "Plastic Trashcan (Large)", "brand": "-", "qty": 46, "price": 1000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "플라스틱 쓰레기통 (소)", "name_en": "Plastic Trashcan (Small)", "brand": "-", "qty": 2, "price": 1000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "철제 쓰레기통", "name_en": "Metal Trashcan", "brand": "-", "qty": 3, "price": 1000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "원목 모니터 받침대", "name_en": "Wooden Monitor Stand", "brand": "-", "qty": 21, "price": 3000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "원목 선반", "name_en": "Wooden Shelf", "brand": "-", "qty": 6, "price": 10000, "notes": "창고", "notes_en": "Storage"},
    {"category": "가구", "category_en": "Furniture", "name": "구루마", "name_en": "Vertical Dolly", "brand": "-", "qty": 1, "price": 50000, "notes": "창고", "notes_en": "Storage"},
    {"category": "가구", "category_en": "Furniture", "name": "원목 테이블 (중)", "name_en": "Wooden Table (Medium)", "brand": "Fursys", "qty": 2, "price": 40000, "notes": "실험실 앞", "notes_en": "Front of Lab"},
    # 전자기기 / Electronics
    {"category": "전자기기", "category_en": "Electronics", "name": "스탠드", "name_en": "Desk Lamp", "brand": "PAPA P800B", "qty": 2, "price": 15000, "notes": "", "notes_en": ""},
    {"category": "전자기기", "category_en": "Electronics", "name": "천장형 에어컨", "name_en": "Ceiling AC", "brand": "Whisen", "qty": 3, "price": 150000, "notes": "실험실", "notes_en": "Lab"},
    {"category": "전자기기", "category_en": "Electronics", "name": "프로젝터 (EB-UO5)", "name_en": "Projector (EB-UO5)", "brand": "Epson", "qty": 1, "price": 40000, "notes": "회의실 3", "notes_en": "Meeting Room 3"},
    {"category": "전자기기", "category_en": "Electronics", "name": "프로젝터 (EB-2255U)", "name_en": "Projector (EB-2255U)", "brand": "Epson", "qty": 1, "price": 100000, "notes": "회의실 4", "notes_en": "Meeting Room 4"},
    {"category": "전자기기", "category_en": "Electronics", "name": "냉장고", "name_en": "Fridge", "brand": "LG", "qty": 1, "price": 150000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "전자기기", "category_en": "Electronics", "name": "음료수 냉장고", "name_en": "Drink Fridge", "brand": "Turboair", "qty": 1, "price": 90000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "전자기기", "category_en": "Electronics", "name": "TV (43in)", "name_en": "TV (43in)", "brand": "theham", "qty": 1, "price": 30000, "notes": "회의실 1", "notes_en": "Meeting Room 1"},
    {"category": "전자기기", "category_en": "Electronics", "name": "TV (55in)", "name_en": "TV (55in)", "brand": "theham", "qty": 2, "price": 40000, "notes": "회의실 2, 4", "notes_en": "Meeting Room 2, 4"},
    {"category": "전자기기", "category_en": "Electronics", "name": "TV (65in)", "name_en": "TV (65in)", "brand": "LG", "qty": 1, "price": 50000, "notes": "입구", "notes_en": "Entrance"},
    {"category": "전자기기", "category_en": "Electronics", "name": "TV (38in)", "name_en": "TV (38in)", "brand": "LG", "qty": 1, "price": 30000, "notes": "입구", "notes_en": "Entrance"},
    {"category": "전자기기", "category_en": "Electronics", "name": "미니 냉장고", "name_en": "Mini Fridge", "brand": "SMEG", "qty": 1, "price": 150000, "notes": "", "notes_en": ""},
    {"category": "전자기기", "category_en": "Electronics", "name": "커피머신", "name_en": "Coffee Machine", "brand": "SMEG", "qty": 1, "price": 80000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "전자기기", "category_en": "Electronics", "name": "와인냉장고", "name_en": "Wine Fridge", "brand": "LG", "qty": 1, "price": 70000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "전자기기", "category_en": "Electronics", "name": "전자레인지", "name_en": "Microwave", "brand": "LG", "qty": 1, "price": 10000, "notes": "탕비실", "notes_en": "Break Room"},
    {"category": "전자기기", "category_en": "Electronics", "name": "선풍기 (대)", "name_en": "Fan (Large)", "brand": "Paesco", "qty": 3, "price": 30000, "notes": "", "notes_en": ""},
    {"category": "전자기기", "category_en": "Electronics", "name": "선풍기 (소)", "name_en": "Fan (Small)", "brand": "Paesco", "qty": 4, "price": 20000, "notes": "", "notes_en": ""},
    {"category": "전자기기", "category_en": "Electronics", "name": "시계", "name_en": "Clock", "brand": "Quartz", "qty": 2, "price": 5000, "notes": "회의실 3, 실험실", "notes_en": "Meeting Room 3, Lab"},
    {"category": "전자기기", "category_en": "Electronics", "name": "에어컨", "name_en": "AC", "brand": "Whisen", "qty": 1, "price": 200000, "notes": "회의실 3", "notes_en": "Meeting Room 3"},
    {"category": "전자기기", "category_en": "Electronics", "name": "안마의자", "name_en": "Massage Chair", "brand": "BodyFriend VENTARS", "qty": 1, "price": 300000, "notes": "휴게 공간", "notes_en": "Rest Area"},
    {"category": "전자기기", "category_en": "Electronics", "name": "스탠딩 책상", "name_en": "Standing Desk", "brand": "Fursys", "qty": 2, "price": 200000, "notes": "Working Space 1, 2", "notes_en": "Working Space 1, 2"},
    {"category": "전자기기", "category_en": "Electronics", "name": "문서파쇄기 2300N", "name_en": "2300N Paper Shredder", "brand": "Sindoh", "qty": 1, "price": 60000, "notes": "", "notes_en": ""},
    # 추가 항목
    {"category": "전자기기", "category_en": "Electronics", "name": "마샬 스피커", "name_en": "Marshall Speaker", "brand": "Marshall", "qty": 1, "price": 50000, "notes": "", "notes_en": ""},
    {"category": "전자기기", "category_en": "Electronics", "name": "Blue Yeti A00104 마이크", "name_en": "Blue Yeti A00104 Microphone", "brand": "Blue Yeti", "qty": 1, "price": 40000, "notes": "", "notes_en": ""},
    {"category": "가구", "category_en": "Furniture", "name": "와이어링 제본기 WS-3200", "name_en": "Wiring Binding Machine WS-3200", "brand": "와이어링", "qty": 1, "price": 50000, "notes": "", "notes_en": ""},
]
