# All items from Excel + manually added Marshall speaker
# Fields: category, name, brand, qty, price, notes

ITEMS = [
    # 가구
    {"category": "가구", "name": "책상 - 일자형", "brand": "Fursys", "qty": 36, "price": 50000, "notes": ""},
    {"category": "가구", "name": "책상 - 120도 책상", "brand": "Fursys", "qty": 6, "price": 40000, "notes": ""},
    {"category": "가구", "name": "사무용 의자", "brand": "Fursys", "qty": 42, "price": 30000, "notes": ""},
    {"category": "가구", "name": "탕비실 철제 스툴", "brand": "-", "qty": 16, "price": 5000, "notes": "탕비실"},
    {"category": "가구", "name": "탕비실 플라스틱 우드 스툴", "brand": "-", "qty": 7, "price": 5000, "notes": "탕비실"},
    {"category": "가구", "name": "빈백", "brand": "요기보", "qty": 5, "price": 25000, "notes": "탕비실"},
    {"category": "가구", "name": "Fursys 반인분 소파", "brand": "Fursys", "qty": 2, "price": 50000, "notes": ""},
    {"category": "가구", "name": "Fursys 긴 브라운 테이블", "brand": "Fursys", "qty": 1, "price": 80000, "notes": ""},
    {"category": "가구", "name": "브라운 의자", "brand": "-", "qty": 12, "price": 41800, "notes": ""},
    {"category": "가구", "name": "브라운 소파", "brand": "-", "qty": 1, "price": 50000, "notes": ""},
    {"category": "가구", "name": "회의실 의자", "brand": "Fursys", "qty": 39, "price": 20000, "notes": "회의실 1-4"},
    {"category": "가구", "name": "회의실 1 책상", "brand": "Fursys", "qty": 1, "price": 50000, "notes": "회의실 1"},
    {"category": "가구", "name": "회의실 2 책상", "brand": "Fursys", "qty": 1, "price": 60000, "notes": "회의실 2"},
    {"category": "가구", "name": "회의실 3 책상", "brand": "Fursys", "qty": 1, "price": 70000, "notes": "회의실 3"},
    {"category": "가구", "name": "회의실 4 책상", "brand": "Fursys", "qty": 1, "price": 60000, "notes": "회의실 4"},
    {"category": "가구", "name": "사무실 메인 공간 테이블", "brand": "-", "qty": 1, "price": 20000, "notes": ""},
    {"category": "가구", "name": "소형 원형 커피 테이블", "brand": "-", "qty": 1, "price": 10000, "notes": "입구"},
    {"category": "가구", "name": "탕비실 우드 슬랩 테이블 (대)", "brand": "-", "qty": 1, "price": 70000, "notes": "탕비실"},
    {"category": "가구", "name": "탕비실 우드 슬랩 테이블 (소)", "brand": "-", "qty": 1, "price": 50000, "notes": "탕비실"},
    {"category": "가구", "name": "탕비실 타원형 테이블", "brand": "-", "qty": 1, "price": 45000, "notes": "탕비실"},
    {"category": "가구", "name": "탕비실 타원형 테이블 의자", "brand": "-", "qty": 4, "price": 15000, "notes": "탕비실"},
    {"category": "가구", "name": "탕비실 원형 테이블", "brand": "-", "qty": 2, "price": 20000, "notes": "탕비실"},
    {"category": "가구", "name": "탕비실 원형 테이블 의자", "brand": "-", "qty": 2, "price": 15000, "notes": "탕비실"},
    {"category": "가구", "name": "입구 회의실 의자", "brand": "-", "qty": 6, "price": 25000, "notes": "입구"},
    {"category": "가구", "name": "입구 소파", "brand": "KTA 한국TA", "qty": 2, "price": 50000, "notes": "입구"},
    {"category": "가구", "name": "입구 옆 회의실 테이블", "brand": "-", "qty": 1, "price": 30000, "notes": "입구"},
    {"category": "가구", "name": "빨간색 쿠션 스툴", "brand": "Fursys", "qty": 4, "price": 10000, "notes": ""},
    {"category": "가구", "name": "미디어룸 테이블 (대)", "brand": "-", "qty": 2, "price": 30000, "notes": "미디어룸"},
    {"category": "가구", "name": "미디어룸 테이블 (소)", "brand": "-", "qty": 1, "price": 15000, "notes": "미디어룸"},
    {"category": "가구", "name": "(대) 활장 스탠드", "brand": "-", "qty": 1, "price": 40000, "notes": "입구"},
    {"category": "가구", "name": "가죽 의자", "brand": "-", "qty": 1, "price": 40000, "notes": "입구"},
    {"category": "가구", "name": "낮은 커피 테이블", "brand": "-", "qty": 1, "price": 20000, "notes": "입구"},
    {"category": "가구", "name": "선반 (대)", "brand": "-", "qty": 1, "price": 20000, "notes": "Working Space 1"},
    {"category": "가구", "name": "선반 (중)", "brand": "-", "qty": 1, "price": 10000, "notes": "Working Space 1"},
    {"category": "가구", "name": "서랍형 선반", "brand": "-", "qty": 1, "price": 25000, "notes": "Working Space 앞"},
    {"category": "가구", "name": "캐비닛", "brand": "-", "qty": 1, "price": 40000, "notes": "Working Space 앞"},
    {"category": "가구", "name": "사물함", "brand": "-", "qty": 1, "price": 80000, "notes": "Working Space 앞"},
    {"category": "가구", "name": "침대", "brand": "-", "qty": 1, "price": 25000, "notes": "휴게 공간"},
    {"category": "가구", "name": "끌차", "brand": "-", "qty": 2, "price": 20000, "notes": "창고"},
    {"category": "가구", "name": "사다리 (대)", "brand": "-", "qty": 1, "price": 70000, "notes": "창고"},
    {"category": "가구", "name": "화분 선반", "brand": "-", "qty": 3, "price": 10000, "notes": ""},
    {"category": "가구", "name": "플라스틱 쓰레기통 (대)", "brand": "-", "qty": 46, "price": 3000, "notes": ""},
    {"category": "가구", "name": "플라스틱 쓰레기통 (소)", "brand": "-", "qty": 2, "price": 2000, "notes": ""},
    {"category": "가구", "name": "철제 쓰레기통", "brand": "-", "qty": 3, "price": 3000, "notes": ""},
    {"category": "가구", "name": "원목 모니터 받침대", "brand": "-", "qty": 21, "price": 3000, "notes": ""},
    {"category": "가구", "name": "원목 선반", "brand": "-", "qty": 6, "price": 10000, "notes": "창고"},
    {"category": "가구", "name": "구루마", "brand": "-", "qty": 1, "price": 50000, "notes": "창고"},
    {"category": "가구", "name": "원목 테이블 (중)", "brand": "Fursys", "qty": 2, "price": 40000, "notes": "실험실 앞"},
    # 전자기기
    {"category": "전자기기", "name": "스탠드", "brand": "PAPA P800B", "qty": 2, "price": 15000, "notes": ""},
    {"category": "전자기기", "name": "천장형 에어컨", "brand": "Whisen", "qty": 3, "price": 150000, "notes": "실험실"},
    {"category": "전자기기", "name": "프로젝터 (EB-UO5)", "brand": "Epson", "qty": 1, "price": 40000, "notes": "회의실 3"},
    {"category": "전자기기", "name": "프로젝터 (EB-2255U)", "brand": "Epson", "qty": 1, "price": 100000, "notes": "회의실 4"},
    {"category": "전자기기", "name": "냉장고", "brand": "LG", "qty": 1, "price": 150000, "notes": "탕비실"},
    {"category": "전자기기", "name": "음료수 냉장고", "brand": "Turboair", "qty": 1, "price": 90000, "notes": "탕비실"},
    {"category": "전자기기", "name": "TV (43in)", "brand": "theham", "qty": 1, "price": 30000, "notes": "회의실 1"},
    {"category": "전자기기", "name": "TV (55in)", "brand": "theham", "qty": 2, "price": 40000, "notes": "회의실 2, 4"},
    {"category": "전자기기", "name": "TV (65in)", "brand": "LG", "qty": 1, "price": 50000, "notes": "입구"},
    {"category": "전자기기", "name": "TV (38in)", "brand": "LG", "qty": 1, "price": 30000, "notes": "입구"},
    {"category": "전자기기", "name": "미니 냉장고", "brand": "SMEG", "qty": 1, "price": 150000, "notes": ""},
    {"category": "전자기기", "name": "커피머신", "brand": "SMEG", "qty": 1, "price": 80000, "notes": "탕비실"},
    {"category": "전자기기", "name": "와인냉장고", "brand": "LG", "qty": 1, "price": 70000, "notes": "탕비실"},
    {"category": "전자기기", "name": "전자레인지", "brand": "LG", "qty": 1, "price": 10000, "notes": "탕비실"},
    {"category": "전자기기", "name": "선풍기 (대)", "brand": "Paesco", "qty": 3, "price": 30000, "notes": ""},
    {"category": "전자기기", "name": "선풍기 (소)", "brand": "Paesco", "qty": 4, "price": 20000, "notes": ""},
    {"category": "전자기기", "name": "시계", "brand": "Quartz", "qty": 2, "price": 5000, "notes": "회의실 3, 실험실"},
    {"category": "전자기기", "name": "에어컨", "brand": "Whisen", "qty": 1, "price": 200000, "notes": "회의실 3"},
    {"category": "전자기기", "name": "안마의자", "brand": "BodyFriend VENTARS", "qty": 1, "price": 300000, "notes": "휴게 공간"},
    {"category": "전자기기", "name": "스탠딩 책상", "brand": "Fursys", "qty": 2, "price": 200000, "notes": "Working Space 1, 2"},
    {"category": "전자기기", "name": "문서파쇄기 2300N", "brand": "Sindoh", "qty": 1, "price": 60000, "notes": ""},
    # 추가 항목
    {"category": "전자기기", "name": "마샬 스피커", "brand": "Marshall", "qty": 1, "price": 50000, "notes": ""},
]
